import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Four Scenarios for Virginia — Virginia AI Futures",
  description:
    "Four plausible futures for Virginia's SMB economy based on AI fluency depth and geographic reach of knowledge networks.",
  openGraph: {
    title: "Ch 4: Four Scenarios for Virginia",
    description:
      "Plausible futures generated by crossing two critical uncertainties: fluency depth and geographic reach.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ch 4: Four Scenarios for Virginia",
    description:
      "Plausible futures generated by crossing two critical uncertainties: fluency depth and geographic reach.",
  },
};

export default function Ch4Page() {
  return (
    <div className="flex min-h-screen bg-bg-page">
      <Sidebar />

      <div className="flex-1 flex flex-col overflow-y-auto pb-[72px] md:pb-0">
        {/* Dark Header */}
        <div
          className="w-full flex flex-col items-center justify-center text-center bg-bg-sidebar py-10 px-6 md:px-20 md:h-[360px]"
        >
          <div className="space-y-4">
            <p className="text-[11px] font-semibold uppercase text-accent-crimson" style={{ letterSpacing: "1px" }}>
              Chapter 4
            </p>
            <h1
              className="text-[36px] md:text-[64px] font-medium text-text-on-dark"
              style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", letterSpacing: "-2px" }}
            >
              Four Scenarios for Virginia
            </h1>
            <p className="text-text-tertiary text-[14px] md:text-[16px] text-center mx-auto" style={{ lineHeight: 1.5, maxWidth: 800 }}>
              Plausible futures generated by crossing two critical uncertainties: fluency depth and geographic reach.
            </p>
          </div>
        </div>

        {/* Content Area */}
        <div className="space-y-12 max-w-[1104px] mx-auto px-6 md:px-8" style={{ paddingTop: 60, paddingBottom: 60 }}>

          {/* CTA Bar */}
          <div className="flex justify-end">
            <Link
              href="/assess"
              className="inline-flex items-center px-4 py-2 rounded-full bg-accent-crimson text-[13px] font-medium text-white hover:bg-accent-crimson/90 transition-colors"
            >
              Analyze Your Business →
            </Link>
          </div>

          {/* Fiction Disclaimer */}
          <div
            className="flex items-center gap-3"
            style={{ border: "1px solid #E0E0E0", padding: "16px 24px" }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#999999" strokeWidth="2" className="shrink-0">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
            </svg>
            <p className="text-text-secondary text-[13px] leading-[1.5]">
              These scenarios are works of structured fiction, not predictions. They are designed to provoke strategic questions for business leaders and policy makers. Elements of each could emerge. No single scenario will materialize as described.
            </p>
          </div>

          {/* Body + Margin Row */}
          <div className="flex flex-col md:flex-row gap-12">
            <div className="flex-1 space-y-6">
              <p className="text-text-primary text-[16px]" style={{ lineHeight: 1.7 }}>
                The two critical uncertainties from this analysis define the scenario space: how far beyond surface-level adoption will businesses progress, and whether the knowledge networks that enable deeper engagement will extend beyond the metro areas where they currently concentrate. Crossing those variables produces four plausible futures for Virginia&apos;s SMB economy, each grounded in the economic and geographic dynamics documented in the preceding chapters.
              </p>
              <p className="text-text-primary text-[16px]" style={{ lineHeight: 1.7 }}>
                Each scenario is a standalone narrative. Read them in any order. Look for the one that feels most like your market, your community, your business.
              </p>
            </div>
            <div className="w-full md:w-[280px] md:shrink-0">
              <div className="space-y-3" style={{ paddingLeft: 24, borderLeft: "3px solid #C41E3A" }}>
                <p className="text-[13px] font-semibold text-text-primary">Shell&apos;s Scenario Planning</p>
                <p className="text-text-secondary text-[13px]" style={{ lineHeight: 1.6 }}>
                  Developed at Royal Dutch Shell in the early 1970s by Pierre Wack and Ted Newland. The goal is not prediction but preparation: making strategic decisions that perform well across different outcomes.
                </p>
              </div>
            </div>
          </div>

          {/* Scenario Matrix — Desktop */}
          <div className="hidden md:block relative" style={{ width: 1104, height: 552 }}>
            {/* Horizontal axis line */}
            <div
              className="absolute"
              style={{ top: 276, left: 0, width: 1104, height: 1, backgroundColor: "#E0E0E0" }}
            />
            {/* Vertical axis line */}
            <div
              className="absolute"
              style={{ left: 552, top: 36, width: 1, height: 480, backgroundColor: "#E0E0E0" }}
            />

            {/* Axis Labels */}
            <p
              className="absolute text-center text-text-tertiary"
              style={{ top: 8, left: 477, width: 150, fontFamily: "Inter, sans-serif", fontSize: 9, fontWeight: 600, letterSpacing: "1.5px" }}
            >
              DEEP FLUENCY
            </p>
            <p
              className="absolute text-center text-text-tertiary"
              style={{ top: 530, left: 452, width: 200, fontFamily: "Inter, sans-serif", fontSize: 9, fontWeight: 600, letterSpacing: "1.5px" }}
            >
              SHALLOW FLUENCY
            </p>
            <p
              className="absolute text-left text-text-tertiary"
              style={{ top: 282, left: 8, fontFamily: "Inter, sans-serif", fontSize: 9, fontWeight: 600, letterSpacing: "1.5px" }}
            >
              CONCENTRATED KNOWLEDGE
            </p>
            <p
              className="absolute text-right text-text-tertiary"
              style={{ top: 282, left: 884, width: 220, fontFamily: "Inter, sans-serif", fontSize: 9, fontWeight: 600, letterSpacing: "1.5px" }}
            >
              DISTRIBUTED KNOWLEDGE
            </p>

            {/* Top-left: Pockets of Excellence */}
            <Link href="/scenarios/pockets-of-excellence">
              <div
                className="absolute flex flex-col hover:border-text-secondary transition-colors"
                style={{ top: 36, left: 0, width: 540, height: 216, padding: 24, border: "1px solid #E0E0E0", borderRadius: 4, gap: 12 }}
              >
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>DEEP &amp; CONCENTRATED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Pockets of Excellence&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Deep fluency forms in metro clusters while most of the state remains at platform level.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>

            {/* Top-right: Build It Yourself */}
            <Link href="/scenarios/build-it-yourself">
              <div
                className="absolute flex flex-col hover:border-text-secondary transition-colors"
                style={{ top: 36, left: 564, width: 540, height: 216, padding: 24, border: "1px solid #E0E0E0", borderRadius: 4, gap: 12 }}
              >
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>DEEP &amp; DISTRIBUTED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Build It Yourself&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Broad fluency spreads through peer networks across Virginia&apos;s geography.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>

            {/* Bottom-left: The Widening Gap */}
            <Link href="/scenarios/the-widening-gap">
              <div
                className="absolute flex flex-col hover:border-text-secondary transition-colors"
                style={{ top: 300, left: 0, width: 540, height: 216, padding: 24, border: "1px solid #E0E0E0", borderRadius: 4, gap: 12 }}
              >
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>SHALLOW &amp; CONCENTRATED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;The Widening Gap&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  A trust shock or recession during the critical window hardens the fluency divide.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>

            {/* Bottom-right: Software Does It For You */}
            <Link href="/scenarios/software-does-it">
              <div
                className="absolute flex flex-col hover:border-text-secondary transition-colors"
                style={{ top: 300, left: 564, width: 540, height: 216, padding: 24, border: "1px solid #E0E0E0", borderRadius: 4, gap: 12 }}
              >
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>SHALLOW &amp; DISTRIBUTED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Software Does It For You&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Platform-delivered AI creates broad but shallow adoption. The inoculation effect.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>
          </div>

          {/* Scenario Cards — Mobile */}
          <div className="grid grid-cols-1 gap-4 md:hidden">
            <Link href="/scenarios/pockets-of-excellence">
              <div className="flex flex-col p-6 border border-[#E0E0E0] rounded gap-3 hover:border-text-secondary transition-colors">
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>DEEP &amp; CONCENTRATED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Pockets of Excellence&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Deep fluency forms in metro clusters while most of the state remains at platform level.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>
            <Link href="/scenarios/build-it-yourself">
              <div className="flex flex-col p-6 border border-[#E0E0E0] rounded gap-3 hover:border-text-secondary transition-colors">
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>DEEP &amp; DISTRIBUTED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Build It Yourself&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Broad fluency spreads through peer networks across Virginia&apos;s geography.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>
            <Link href="/scenarios/the-widening-gap">
              <div className="flex flex-col p-6 border border-[#E0E0E0] rounded gap-3 hover:border-text-secondary transition-colors">
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>SHALLOW &amp; CONCENTRATED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;The Widening Gap&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  A trust shock or recession during the critical window hardens the fluency divide.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>
            <Link href="/scenarios/software-does-it">
              <div className="flex flex-col p-6 border border-[#E0E0E0] rounded gap-3 hover:border-text-secondary transition-colors">
                <div className="inline-flex self-start" style={{ backgroundColor: "#C41E3A", borderRadius: 4, padding: "6px 12px" }}>
                  <span style={{ fontFamily: "Inter, sans-serif", fontSize: 10, fontWeight: 600, letterSpacing: "0.5px", color: "#FAFAF7" }}>SHALLOW &amp; DISTRIBUTED</span>
                </div>
                <p style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 24, fontWeight: 500, color: "#0F0F0F" }}>
                  &ldquo;Software Does It For You&rdquo;
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 13, fontWeight: 400, lineHeight: 1.5, color: "#666666" }}>
                  Platform-delivered AI creates broad but shallow adoption. The inoculation effect.
                </p>
                <p style={{ fontFamily: "Inter, sans-serif", fontSize: 14, fontWeight: 400, color: "#C41E3A" }}>
                  Read this scenario →
                </p>
              </div>
            </Link>
          </div>

          {/* Bottom Navigation */}
          <div className="flex justify-between items-center" style={{ borderTop: "1px solid #E0E0E0", paddingTop: 32 }}>
            <Link href="/ch3" className="text-text-secondary text-[14px] hover:underline">
              ← Ch 3: Knowledge Networks
            </Link>
            <Link href="/ch5" className="text-accent-crimson text-[14px] hover:underline">
              Ch 5: Implications →
            </Link>
          </div>

          {/* Footer */}
          <div className="flex flex-col md:flex-row gap-4 md:gap-0 justify-between items-center pb-4">
            <div className="flex gap-6">
              <Link href="/privacy" className="text-[12px] text-text-tertiary hover:text-text-secondary">Privacy</Link>
              <Link href="/legal" className="text-[12px] text-text-tertiary hover:text-text-secondary">Legal</Link>
              <a href="https://buildfirst.io" target="_blank" rel="noopener noreferrer" className="text-[12px] text-text-tertiary hover:text-text-secondary">buildfirst.io</a>
            </div>
            <span className="text-[12px] text-text-tertiary">Virginia AI Futures is a BuildFirst research project</span>
          </div>
        </div>
      </div>
    </div>
  );
}
